export const types = {
  FETCH_ALBUMS: 'FETCH_ALBUMS',
  UPDATE_CURRENT_ALBUM: 'UPDATE_CURRENT_ALBUM',
  UPDATE_DEVELOPING_ALBUM: 'UPDATE_DEVELOPING_ALBUM',
  SET_DEVELOPING_AVIABLE: 'DEVELOPING_AVIABLE',
  RENDER_ALBUM: 'RENDER_ALBUM',
  SET_PIC_INDEX: 'SET_PIC_INDEX',
  INCREMENT_PIC_INDEX: 'INCREMENT_PIC_INDEX',
  SET_EXPIRATION_DATE: 'SET_EXPIRATION_DATE',
}